spring:
  application:
    name: server-config
  cloud:
    config:
      server:
        svn:
          uri: https://github.com/dongwenqiang002/horcrux-kuliao/trunk/horcrux-config      #���òֿ�
          username: roseJoke
          password: 100715
          search-paths: https://github.com/dongwenqiang002/horcrux-kuliao.git

#  uri: https://172.16.0.25/svn/kim_project/trunk/babel_horcrux/horcrux-config  #���òֿ�
#   username: yong.xu
#   password: password123                ���Լ����Git�ֿ�   https://github.com/roseJoke/BlossomRose-.git#  uri: https://172.16.0.25/svn/kim_project/trunk/babel_horcrux/horcrux-config  #���òֿ�
#   username: yong.xu
#   password: password123                ���Լ����Git�ֿ�   https://github.com/roseJoke/BlossomRose-.git#  uri: https://172.16.0.25/svn/kim_project/trunk/babel_horcrux/horcrux-config  #���òֿ�
#   username: yong.xu
#   password: password123                ���Լ����Git�ֿ�   https://github.com/roseJoke/BlossomRose-.git#  uri: https://172.16.0.25/svn/kim_project/trunk/babel_horcrux/horcrux-config  #���òֿ�
#   username: yong.xu
#   password: password123                ���Լ����Git�ֿ�   https://github.com/roseJoke/BlossomRose-.git#  uri: https://172.16.0.25/svn/kim_project/trunk/babel_horcrux/horcrux-config  #���òֿ�
#   username: yong.xu
#   password: password123                ���Լ����Git�ֿ�   https://github.com/roseJoke/BlossomRose-.git#  uri: https://172.16.0.25/svn/kim_project/trunk/babel_horcrux/horcrux-config  #���òֿ�
#   username: yong.xu
#   password: password123                ���Լ����Git�ֿ�   https://github.com/roseJoke/BlossomRose-.git#  uri: https://172.16.0.25/svn/kim_project/trunk/babel_horcrux/horcrux-config  #���òֿ�
#   username: yong.xu
#   password: password123                ���Լ����Git�ֿ�   https://github.com/roseJoke/BlossomRose-.git#  uri: https://172.16.0.25/svn/kim_project/trunk/babel_horcrux/horcrux-config  #���òֿ�
#   username: yong.xu
#   password: password123                ���Լ����Git�ֿ�   https://github.com/roseJoke/BlossomRose-.git#  uri: https://172.16.0.25/svn/kim_project/trunk/babel_horcrux/horcrux-config  #���òֿ�
#   username: yong.xu
#   password楼是的发送到挥发分 水电费那速度来看你发货后离开东三省，代码发顺丰 斯卡迪部分就开始电风扇   : password123                ���Լ����Git�ֿ�   https://github.com/roseJoke/BlossomRose-.git