spring:
  application:
    name: server-config
  cloud:
    config:
      server:
        svn:
          uri: https://github.com/dongwenqiang002/horcrux-kuliao/trunk/horcrux-config      #���òֿ�
          username: roseJoke
          password: 100715
          search-paths: https://github.com/dongwenqiang002/horcrux-kuliao.git
